version: "3.7"

services:
  mysql:
    image: mysql:latest
    volumes:
      - ./.db:/var/lib/mysql:cached
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
